data:
    lang: zh
    name: cmrc2018
    split: dev-v1.1.json
ranker:
    use_cached: True
    cached_ranker_file: cmrc2018_dev_zh-wiki-frame-2018_sparta.json
reader:
    model_id: cmrc2018-ds-context-global-norm-2018sparta-from-pt-v1
param:
    score_weight: 0.8
    top_k: 50